name: PhantomJS
markdown: redcarpet
pygments: true
githubEdit: https://github.com/JamieMason/phantomjs/edit/docs/_posts

# When pushing to GitHub
url: http://jamiemason.github.io/phantomjs

# When Developing Locally
# url: http://localhost:4000
